// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (
    cart_id,
    product_id,
    variant_id,
    quantity
) VALUES (
    $1, $2, $3, $4
) 
ON CONFLICT (cart_id, product_id, COALESCE(variant_id, '00000000-0000-0000-0000-000000000000'::uuid)) 
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, variant_id, quantity, created_at
`

type AddCartItemParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem,
		arg.CartID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
    session_id,
    user_id,
    status
) VALUES (
    $1, $2, 'active'
) RETURNING id, session_id, user_id, status, created_at, updated_at
`

type CreateCartParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.SessionID, arg.UserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const getCartBySession = `-- name: GetCartBySession :one
SELECT id, session_id, user_id, status, created_at, updated_at FROM carts
WHERE session_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetCartBySession(ctx context.Context, sessionID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartBySession, sessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUser = `-- name: GetCartByUser :one
SELECT id, session_id, user_id, status, created_at, updated_at FROM carts
WHERE user_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetCartByUser(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.variant_id, ci.quantity, ci.created_at, p.title as product_title, p.base_price, p.is_digital, p.file_path,
       pv.title as variant_title, pv.price as variant_price
FROM cart_items ci
JOIN products p ON ci.product_id = p.id
LEFT JOIN product_variants pv ON ci.variant_id = pv.id
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC
`

type GetCartItemsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CartID       pgtype.UUID        `json:"cart_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	VariantID    pgtype.UUID        `json:"variant_id"`
	Quantity     int32              `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProductTitle string             `json:"product_title"`
	BasePrice    pgtype.Numeric     `json:"base_price"`
	IsDigital    *bool              `json:"is_digital"`
	FilePath     *string            `json:"file_path"`
	VariantTitle *string            `json:"variant_title"`
	VariantPrice pgtype.Numeric     `json:"variant_price"`
}

func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.VariantID,
			&i.Quantity,
			&i.CreatedAt,
			&i.ProductTitle,
			&i.BasePrice,
			&i.IsDigital,
			&i.FilePath,
			&i.VariantTitle,
			&i.VariantPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE id = $1 AND cart_id = $2
`

type RemoveCartItemParams struct {
	ID     pgtype.UUID `json:"id"`
	CartID pgtype.UUID `json:"cart_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.ID, arg.CartID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $3
WHERE id = $1 AND cart_id = $2
RETURNING id, cart_id, product_id, variant_id, quantity, created_at
`

type UpdateCartItemQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	CartID   pgtype.UUID `json:"cart_id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.CartID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const updateCartUser = `-- name: UpdateCartUser :exec
UPDATE carts
SET user_id = $2
WHERE id = $1
`

type UpdateCartUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCartUser(ctx context.Context, arg UpdateCartUserParams) error {
	_, err := q.db.Exec(ctx, updateCartUser, arg.ID, arg.UserID)
	return err
}
