// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (
    name,
    slug,
    parent_id,
    is_active
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, slug, parent_id, is_active
`

type CreateCategoryParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
	IsActive *bool       `json:"is_active"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    title,
    slug,
    description,
    base_price,
    is_digital,
    file_path,
    category_id,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, title, slug, description, base_price, is_digital, file_path, category_id, is_active, created_at
`

type CreateProductParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description *string        `json:"description"`
	BasePrice   pgtype.Numeric `json:"base_price"`
	IsDigital   *bool          `json:"is_digital"`
	FilePath    *string        `json:"file_path"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	IsActive    *bool          `json:"is_active"`
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BasePrice,
		arg.IsDigital,
		arg.FilePath,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.IsDigital,
		&i.FilePath,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one

INSERT INTO product_variants (
    product_id,
    title,
    options,
    price,
    compare_at_price,
    sku,
    stock_quantity,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, product_id, title, options, price, compare_at_price, sku, stock_quantity, is_active
`

type CreateProductVariantParams struct {
	ProductID      pgtype.UUID    `json:"product_id"`
	Title          string         `json:"title"`
	Options        []byte         `json:"options"`
	Price          pgtype.Numeric `json:"price"`
	CompareAtPrice pgtype.Numeric `json:"compare_at_price"`
	Sku            *string        `json:"sku"`
	StockQuantity  *int32         `json:"stock_quantity"`
	IsActive       *bool          `json:"is_active"`
}

// Variants
func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Title,
		arg.Options,
		arg.Price,
		arg.CompareAtPrice,
		arg.Sku,
		arg.StockQuantity,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Title,
		&i.Options,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.StockQuantity,
		&i.IsActive,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM product_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, parent_id, is_active FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, title, slug, description, base_price, is_digital, file_path, category_id, is_active, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.IsDigital,
		&i.FilePath,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, title, slug, description, base_price, is_digital, file_path, category_id, is_active, created_at FROM products
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.IsDigital,
		&i.FilePath,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, parent_id, is_active FROM categories
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, title, slug, description, base_price, is_digital, file_path, category_id, is_active, created_at FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.BasePrice,
			&i.IsDigital,
			&i.FilePath,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, title, options, price, compare_at_price, sku, stock_quantity, is_active FROM product_variants
WHERE product_id = $1
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Title,
			&i.Options,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.StockQuantity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET 
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    parent_id = COALESCE($4, parent_id),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, name, slug, parent_id, is_active
`

type UpdateCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     *string     `json:"name"`
	Slug     *string     `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
	IsActive *bool       `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    title = COALESCE($2, title),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    base_price = COALESCE($5, base_price),
    is_digital = COALESCE($6, is_digital),
    file_path = COALESCE($7, file_path),
    category_id = COALESCE($8, category_id),
    is_active = COALESCE($9, is_active)
WHERE id = $1
RETURNING id, title, slug, description, base_price, is_digital, file_path, category_id, is_active, created_at
`

type UpdateProductParams struct {
	ID          pgtype.UUID    `json:"id"`
	Title       *string        `json:"title"`
	Slug        *string        `json:"slug"`
	Description *string        `json:"description"`
	BasePrice   pgtype.Numeric `json:"base_price"`
	IsDigital   *bool          `json:"is_digital"`
	FilePath    *string        `json:"file_path"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	IsActive    *bool          `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.BasePrice,
		arg.IsDigital,
		arg.FilePath,
		arg.CategoryID,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.BasePrice,
		&i.IsDigital,
		&i.FilePath,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
