// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    total_amount,
    status,
    payment_status,
    payment_method
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, guest_info, total_amount, status, traffic_source, payment_status, payment_method, created_at
`

type CreateOrderParams struct {
	UserID        pgtype.UUID     `json:"user_id"`
	TotalAmount   pgtype.Numeric  `json:"total_amount"`
	Status        NullOrderStatus `json:"status"`
	PaymentStatus *string         `json:"payment_status"`
	PaymentMethod *string         `json:"payment_method"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.PaymentStatus,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestInfo,
		&i.TotalAmount,
		&i.Status,
		&i.TrafficSource,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    variation_id,
    quantity,
    price_at_booking,
    title
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, order_id, product_id, variation_id, title, quantity, price_at_booking, download_link_sent
`

type CreateOrderItemParams struct {
	OrderID        pgtype.UUID    `json:"order_id"`
	ProductID      pgtype.UUID    `json:"product_id"`
	VariationID    pgtype.UUID    `json:"variation_id"`
	Quantity       int32          `json:"quantity"`
	PriceAtBooking pgtype.Numeric `json:"price_at_booking"`
	Title          string         `json:"title"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariationID,
		arg.Quantity,
		arg.PriceAtBooking,
		arg.Title,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariationID,
		&i.Title,
		&i.Quantity,
		&i.PriceAtBooking,
		&i.DownloadLinkSent,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, guest_info, total_amount, status, traffic_source, payment_status, payment_method, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestInfo,
		&i.TotalAmount,
		&i.Status,
		&i.TrafficSource,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, product_id, variation_id, title, quantity, price_at_booking, download_link_sent FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariationID,
			&i.Title,
			&i.Quantity,
			&i.PriceAtBooking,
			&i.DownloadLinkSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, guest_info, total_amount, status, traffic_source, payment_status, payment_method, created_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestInfo,
			&i.TotalAmount,
			&i.Status,
			&i.TrafficSource,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, payment_status = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, guest_info, total_amount, status, traffic_source, payment_status, payment_method, created_at
`

type UpdateOrderStatusParams struct {
	ID            pgtype.UUID     `json:"id"`
	Status        NullOrderStatus `json:"status"`
	PaymentStatus *string         `json:"payment_status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.PaymentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestInfo,
		&i.TotalAmount,
		&i.Status,
		&i.TrafficSource,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}
