// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: page_builder.sql

package db

import (
	"context"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (
    route,
    name,
    sections,
    is_published
) VALUES (
    $1, $2, $3, $4
) RETURNING id, route, name, sections, is_published, updated_at
`

type CreatePageParams struct {
	Route       string `json:"route"`
	Name        string `json:"name"`
	Sections    []byte `json:"sections"`
	IsPublished *bool  `json:"is_published"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Route,
		arg.Name,
		arg.Sections,
		arg.IsPublished,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Name,
		&i.Sections,
		&i.IsPublished,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByRoute = `-- name: GetPageByRoute :one
SELECT id, route, name, sections, is_published, updated_at FROM pages
WHERE route = $1 LIMIT 1
`

func (q *Queries) GetPageByRoute(ctx context.Context, route string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByRoute, route)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Name,
		&i.Sections,
		&i.IsPublished,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, route, name, sections, is_published, updated_at FROM pages
ORDER BY updated_at DESC
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Route,
			&i.Name,
			&i.Sections,
			&i.IsPublished,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET 
    sections = $2,
    is_published = $3,
    updated_at = NOW()
WHERE route = $1
RETURNING id, route, name, sections, is_published, updated_at
`

type UpdatePageParams struct {
	Route       string `json:"route"`
	Sections    []byte `json:"sections"`
	IsPublished *bool  `json:"is_published"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage, arg.Route, arg.Sections, arg.IsPublished)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Name,
		&i.Sections,
		&i.IsPublished,
		&i.UpdatedAt,
	)
	return i, err
}
