// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package db

import (
	"context"
)

const createPaymentGateway = `-- name: CreatePaymentGateway :one
INSERT INTO payment_gateways (
    id,
    name,
    config,
    is_test_mode,
    is_active,
    position
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, config, is_test_mode, is_active, position
`

type CreatePaymentGatewayParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Config     []byte `json:"config"`
	IsTestMode *bool  `json:"is_test_mode"`
	IsActive   *bool  `json:"is_active"`
	Position   *int32 `json:"position"`
}

func (q *Queries) CreatePaymentGateway(ctx context.Context, arg CreatePaymentGatewayParams) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, createPaymentGateway,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.IsTestMode,
		arg.IsActive,
		arg.Position,
	)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.IsTestMode,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}

const deletePaymentGateway = `-- name: DeletePaymentGateway :exec
DELETE FROM payment_gateways
WHERE id = $1
`

func (q *Queries) DeletePaymentGateway(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePaymentGateway, id)
	return err
}

const getPaymentGateway = `-- name: GetPaymentGateway :one
SELECT id, name, config, is_test_mode, is_active, position FROM payment_gateways
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentGateway(ctx context.Context, id string) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, getPaymentGateway, id)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.IsTestMode,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}

const listPaymentGateways = `-- name: ListPaymentGateways :many
SELECT id, name, config, is_test_mode, is_active, position FROM payment_gateways
ORDER BY position ASC
`

func (q *Queries) ListPaymentGateways(ctx context.Context) ([]PaymentGateway, error) {
	rows, err := q.db.Query(ctx, listPaymentGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentGateway{}
	for rows.Next() {
		var i PaymentGateway
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.IsTestMode,
			&i.IsActive,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentGateway = `-- name: UpdatePaymentGateway :one
UPDATE payment_gateways
SET 
    name = COALESCE($2, name),
    config = COALESCE($3, config),
    is_test_mode = COALESCE($4, is_test_mode),
    is_active = COALESCE($5, is_active),
    position = COALESCE($6, position)
WHERE id = $1
RETURNING id, name, config, is_test_mode, is_active, position
`

type UpdatePaymentGatewayParams struct {
	ID         string  `json:"id"`
	Name       *string `json:"name"`
	Config     []byte  `json:"config"`
	IsTestMode *bool   `json:"is_test_mode"`
	IsActive   *bool   `json:"is_active"`
	Position   *int32  `json:"position"`
}

func (q *Queries) UpdatePaymentGateway(ctx context.Context, arg UpdatePaymentGatewayParams) (PaymentGateway, error) {
	row := q.db.QueryRow(ctx, updatePaymentGateway,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.IsTestMode,
		arg.IsActive,
		arg.Position,
	)
	var i PaymentGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.IsTestMode,
		&i.IsActive,
		&i.Position,
	)
	return i, err
}
