// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: store_config.sql

package db

import (
	"context"
)

const createStoreConfig = `-- name: CreateStoreConfig :one
INSERT INTO store_configs (
    key,
    value,
    is_encrypted,
    group_name
) VALUES (
    $1, $2, $3, $4
) RETURNING key, value, is_encrypted, group_name, updated_at
`

type CreateStoreConfigParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IsEncrypted *bool  `json:"is_encrypted"`
	GroupName   string `json:"group_name"`
}

func (q *Queries) CreateStoreConfig(ctx context.Context, arg CreateStoreConfigParams) (StoreConfig, error) {
	row := q.db.QueryRow(ctx, createStoreConfig,
		arg.Key,
		arg.Value,
		arg.IsEncrypted,
		arg.GroupName,
	)
	var i StoreConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsEncrypted,
		&i.GroupName,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoreConfig = `-- name: DeleteStoreConfig :exec
DELETE FROM store_configs
WHERE key = $1
`

func (q *Queries) DeleteStoreConfig(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteStoreConfig, key)
	return err
}

const getStoreConfig = `-- name: GetStoreConfig :one
SELECT key, value, is_encrypted, group_name, updated_at FROM store_configs
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetStoreConfig(ctx context.Context, key string) (StoreConfig, error) {
	row := q.db.QueryRow(ctx, getStoreConfig, key)
	var i StoreConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsEncrypted,
		&i.GroupName,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoreConfigs = `-- name: ListStoreConfigs :many
SELECT key, value, is_encrypted, group_name, updated_at FROM store_configs
`

func (q *Queries) ListStoreConfigs(ctx context.Context) ([]StoreConfig, error) {
	rows, err := q.db.Query(ctx, listStoreConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreConfig{}
	for rows.Next() {
		var i StoreConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsEncrypted,
			&i.GroupName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreConfig = `-- name: UpdateStoreConfig :one
UPDATE store_configs
SET 
    value = $2,
    is_encrypted = $3,
    group_name = $4,
    updated_at = now()
WHERE key = $1
RETURNING key, value, is_encrypted, group_name, updated_at
`

type UpdateStoreConfigParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IsEncrypted *bool  `json:"is_encrypted"`
	GroupName   string `json:"group_name"`
}

func (q *Queries) UpdateStoreConfig(ctx context.Context, arg UpdateStoreConfigParams) (StoreConfig, error) {
	row := q.db.QueryRow(ctx, updateStoreConfig,
		arg.Key,
		arg.Value,
		arg.IsEncrypted,
		arg.GroupName,
	)
	var i StoreConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsEncrypted,
		&i.GroupName,
		&i.UpdatedAt,
	)
	return i, err
}
