ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) NOT NULL DEFAULT 'unpaid',
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);

ALTER TABLE order_items
ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '';
