// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package platform

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shop struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Name         string             `json:"name"`
	Subdomain    string             `json:"subdomain"`
	CustomDomain *string            `json:"custom_domain"`
	TenantID     string             `json:"tenant_id"`
	IsActive     *bool              `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID               pgtype.UUID        `json:"id"`
	ShopID           pgtype.UUID        `json:"shop_id"`
	PlanName         string             `json:"plan_name"`
	Status           *string            `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
