// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package platform

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	GetShopBySubdomain(ctx context.Context, subdomain string) (Shop, error)
	ListShopsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Shop, error)
}

var _ Querier = (*Queries)(nil)
