// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shops.sql

package platform

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (
    owner_id,
    name,
    subdomain,
    tenant_id,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner_id, name, subdomain, custom_domain, tenant_id, is_active, created_at
`

type CreateShopParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	Name      string      `json:"name"`
	Subdomain string      `json:"subdomain"`
	TenantID  string      `json:"tenant_id"`
	IsActive  *bool       `json:"is_active"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.OwnerID,
		arg.Name,
		arg.Subdomain,
		arg.TenantID,
		arg.IsActive,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Subdomain,
		&i.CustomDomain,
		&i.TenantID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getShopBySubdomain = `-- name: GetShopBySubdomain :one
SELECT id, owner_id, name, subdomain, custom_domain, tenant_id, is_active, created_at FROM shops
WHERE subdomain = $1 LIMIT 1
`

func (q *Queries) GetShopBySubdomain(ctx context.Context, subdomain string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopBySubdomain, subdomain)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Subdomain,
		&i.CustomDomain,
		&i.TenantID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listShopsByOwner = `-- name: ListShopsByOwner :many
SELECT id, owner_id, name, subdomain, custom_domain, tenant_id, is_active, created_at FROM shops
WHERE owner_id = $1
`

func (q *Queries) ListShopsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Subdomain,
			&i.CustomDomain,
			&i.TenantID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
