// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package checkout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	db "bizbundl/internal/db/sqlc"
	widget "bizbundl/internal/views/components/checkout"
)

func View(props map[string]interface{}) templ.Component {
	var cart db.Cart
	var items []db.GetCartItemsRow
	var isPhysical bool

	if c, ok := props["Cart"].(db.Cart); ok {
		cart = c
	}
	if i, ok := props["Items"].([]db.GetCartItemsRow); ok {
		items = i
	}
	if p, ok := props["IsPhysical"].(bool); ok {
		isPhysical = p
	}

	// For Page Builder Checkout, we default to Cart Mode (Direct Product nil)
	return widget.CheckoutForm(cart, items, nil, nil, isPhysical)
}

var _ = templruntime.GeneratedTemplate
